<?php

return [
    // Serif fonts
    "'Times New Roman', Times, serif",
    "'Georgia', serif",
    "'Garamond', serif",
    "'Palatino Linotype', 'Book Antiqua', Palatino, serif",
    "'Book Antiqua', Palatino, serif",
    "'Cambria', serif",
    "'Constantia', serif",
    "'Baskerville', serif",
    "'Bitter', serif",
    "'Merriweather', serif",
    "'Playfair Display', serif",
    "'Roboto Slab', serif",
    "'PT Serif', serif",
    "'Libre Baskerville', serif",
    "'Crimson Text', serif",
    "'Inknut Antiqua', serif",
    "'Rockwell', serif",
    "'Didot', serif",

    // Sans-serif fonts
    "'Arial', sans-serif",
    "'Arial Black', sans-serif",
    "'Helvetica', sans-serif",
    "'Verdana', sans-serif",
    "'Tahoma', sans-serif",
    "'Trebuchet MS', sans-serif",
    "'Gill Sans', sans-serif",
    "'Futura', sans-serif",
    "'Century Gothic', sans-serif",
    "'Candara', sans-serif",
    "'DejaVu Sans', sans-serif",
    "'Droid Sans', sans-serif",
    "'Exo 2', sans-serif",
    "'Franklin Gothic Medium', sans-serif",
    "'Fira Sans', sans-serif",
    "'Inter', sans-serif",
    "'Josefin Sans', sans-serif",
    "'Karla', sans-serif",
    "'Kanit', sans-serif",
    "'Lato', sans-serif",
    "'Libre Franklin', sans-serif",
    "'Montserrat', sans-serif",
    "'Mukta', sans-serif",
    "'Manrope', sans-serif",
    "'Mukta Malar', sans-serif",
    "'Noto Sans', sans-serif",
    "'Nunito', sans-serif",
    "'Optima', sans-serif",
    "'Open Sans', sans-serif",
    "'Oswald', sans-serif",
    "'Oxygen', sans-serif",
    "'Public Sans', sans-serif",
    "'PT Sans', sans-serif",
    "'Play', sans-serif",
    "'Quicksand', sans-serif",
    "'Roboto', sans-serif",
    "'Raleway', sans-serif",
    "'Segoe UI', sans-serif",
    "'Source Sans Pro', sans-serif",
    "'Signika', sans-serif",
    "'Saira', sans-serif",
    "'Ubuntu', Arial, sans-serif",
    "'Ubuntu', sans-serif",
    "'Varela Round', sans-serif",
    "'Work Sans', sans-serif",
    "'Yantramanav', sans-serif",
    "'Baloo 2', sans-serif",
    "'Hind', sans-serif",
    "'Hind Siliguri', sans-serif",
    "'Hanuman', sans-serif",
    "'Arima Madurai', sans-serif",
    "'arnamu', sans-serif",
    "'tharlon', sans-serif",
    "'xbriyaz', sans-serif",
    "'yahei', sans-serif",
    "'sun-exta', sans-serif",
    "'zawgyi-one', sans-serif",

    // Monospace fonts
    "'Courier New', Courier, monospace",
    "'Courier', monospace",
    "'Consolas', monospace",
    "'Andale Mono', monospace",
    "'Lucida Console', Monaco, monospace",
    "'Monaco', monospace",
    "'PT Mono', monospace",
    "'Source Code Pro', monospace",
    "'Fira Code', monospace",
    "'Inconsolata', monospace",
    "'Cousine', monospace",
    "'Fira Mono', Arial, sans-serif",
    "'Special Elite', monospace",

    // Cursive / Script fonts
    "'Comic Sans MS', cursive, sans-serif",
    "'Brush Script MT', cursive",
    "'Allura', cursive",
    "'Amatic SC', cursive",
    "'Dancing Script', cursive",
    "'Chewy', cursive",
    "'Caveat', cursive",
    "'Fredoka One', cursive",
    "'Great Vibes', cursive",
    "'Lobster', cursive",
    "'Pacifico', cursive",
    "'Patrick Hand', cursive",
    "'Permanent Marker', cursive",
    "'Satisfy', cursive",
    "'Shadows Into Light', cursive",
    "'Baloo Bhaijaan 2', cursive",

    // Hebrew / Israeli fonts
    "'David', serif",
    "'FrankRuehl', serif",
    "'Narkisim', sans-serif",
    "'Guttman Stam', serif",
    "'Miriam', sans-serif",
    "'Cardo', serif",

    // Arabic fonts
    "'Amiri', serif",
    "'Scheherazade', serif",
    "'Cairo', sans-serif",
    "'Droid Arabic Kufi', sans-serif",
    "'Noto Naskh Arabic', serif",

    // Indic / Devanagari fonts
    "'Noto Sans Devanagari', sans-serif",
    "'Noto Serif Devanagari', serif",
    "'Hind Siliguri', sans-serif",
    "'Mukta', sans-serif",
    "'Mukta Malar', sans-serif",
    
    // East Asian fonts
    "'SimSun', serif",
    "'NSimSun', serif",
    "'MingLiU', serif",
    "'PMingLiU', serif",
    "'MS Gothic', sans-serif",
    "'MS Mincho', serif",
    "'Yu Gothic', sans-serif",
    "'Yu Mincho', serif",
    "'Meiryo', sans-serif",
    "'Malgun Gothic', sans-serif",
    "'Microsoft YaHei', sans-serif",
    "'Noto Sans CJK JP', sans-serif",
    "'Noto Sans CJK KR', sans-serif",
    "'Noto Sans CJK SC', sans-serif",
    "'Noto Sans CJK TC', sans-serif",
];
